import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { formatSessionDate } from "@/utils/format-date";
import {
  getFinalAdjustmentsTotal,
  getFinalInvoiceTotal,
  getRemainingFinalPayment,
  getSettlementStatus,
  normalizeFinalAdjustments,
} from "@/lib/final-settlement";
import {
  getBookingServiceLabel,
  normalizeBookingServiceSelections,
} from "@/lib/booking-services";

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

function formatCurrency(n: number) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(n);
}

const labels: Record<string, Record<string, string>> = {
  id: {
    clientDetail: "DETAIL KLIEN",
    service: "Layanan",
    schedule: "Jadwal",
    status: "Status",
    total: "Total",
    subTotal: "Sub Total",
    dpPaid: "DP Dibayar",
    remainingPayment: "Sisa Pembayaran",
    paid: "Lunas",
    unpaid: "Belum Lunas",
    pendingVerification: "Menunggu Verifikasi",
    studioManagement: "Studio Management",
    footerText:
      "Terima kasih atas kepercayaan Anda. Invoice ini digenerate otomatis oleh Client Desk.",
    defaultServiceName: "Layanan",
    invoice: "INVOICE",
    finalInvoice: "INVOICE FINAL",
    adjustments: "Penyesuaian Akhir",
    adjustmentTotal: "Total Penyesuaian",
    noReason: "Tanpa catatan",
  },
  en: {
    clientDetail: "CLIENT DETAIL",
    service: "Service",
    schedule: "Schedule",
    status: "Status",
    total: "Total",
    subTotal: "Sub Total",
    dpPaid: "DP Paid",
    remainingPayment: "Remaining Payment",
    paid: "Paid",
    unpaid: "Unpaid",
    pendingVerification: "Pending Verification",
    studioManagement: "Studio Management",
    footerText:
      "Thank you for your trust. This invoice was auto-generated by Client Desk.",
    defaultServiceName: "Service",
    invoice: "INVOICE",
    finalInvoice: "FINAL INVOICE",
    adjustments: "Final Adjustments",
    adjustmentTotal: "Adjustment Total",
    noReason: "No note",
  },
};

export async function GET(request: NextRequest) {
  const code = request.nextUrl.searchParams.get("code");
  const lang = request.nextUrl.searchParams.get("lang") || "id";
  const stage = request.nextUrl.searchParams.get("stage") || "initial";
  const t = labels[lang] || labels.id;

  if (!code) {
    return NextResponse.json({ error: "Booking code required" }, { status: 400 });
  }

  const { data: booking, error } = await supabaseAdmin
    .from("bookings")
    .select(
      "id, booking_code, client_name, client_whatsapp, session_date, total_price, dp_paid, is_fully_paid, status, settlement_status, final_adjustments, final_payment_amount, final_paid_at, user_id, services(id, name, price, is_addon), booking_services(id, kind, sort_order, service:services(id, name, price, is_addon))",
    )
    .eq("booking_code", code)
    .single();

  if (!booking || error) {
    return NextResponse.json({ error: "Booking not found" }, { status: 404 });
  }

  const { data: profile } = await supabaseAdmin
    .from("profiles")
    .select("studio_name, invoice_logo_url")
    .eq("id", booking.user_id)
    .single();

  const studioName = profile?.studio_name || "Studio";
  const logoBase64 = profile?.invoice_logo_url || null;
  const adjustments = normalizeFinalAdjustments(booking.final_adjustments);
  const adjustmentsTotal = getFinalAdjustmentsTotal(adjustments);
  const finalInvoiceTotal = getFinalInvoiceTotal(booking.total_price, adjustments);
  const isFinalStage = stage === "final";
  const invoiceTitle = isFinalStage ? t.finalInvoice : t.invoice;
  const shownTotal = isFinalStage ? finalInvoiceTotal : booking.total_price;
  const remaining = isFinalStage
    ? getRemainingFinalPayment({
        total_price: booking.total_price,
        dp_paid: booking.dp_paid,
        final_adjustments: adjustments,
        final_payment_amount: booking.final_payment_amount,
        final_paid_at: booking.final_paid_at,
        settlement_status: booking.settlement_status,
        is_fully_paid: booking.is_fully_paid,
      })
    : Math.max(booking.total_price - booking.dp_paid, 0);
  const dateLocale = lang === "en" ? "en-US" : "id-ID";
  const sessionDate = booking.session_date
    ? formatSessionDate(booking.session_date, {
        locale: lang === "en" ? "en" : "id",
        dateOnly: true,
      })
    : "-";
  const now = new Date().toLocaleDateString(dateLocale, {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const serviceSelections = normalizeBookingServiceSelections(
    (booking as { booking_services?: unknown[] }).booking_services,
    booking.services as { id?: string; name: string; price?: number; is_addon?: boolean | null } | null,
  );
  const serviceName = getBookingServiceLabel(serviceSelections, {
    kind: "main",
    fallback: (booking.services as { name?: string } | null)?.name || t.defaultServiceName,
  });
  const settlementStatus = getSettlementStatus(booking.settlement_status);
  const paymentStatus =
    isFinalStage && settlementStatus === "submitted"
      ? t.pendingVerification
      : booking.is_fully_paid
        ? t.paid
        : t.unpaid;

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]);
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const black = rgb(0.1, 0.1, 0.1);
  const gray = rgb(0.42, 0.44, 0.47);
  const lightGray = rgb(0.9, 0.91, 0.92);
  const green = rgb(0.086, 0.64, 0.26);
  const amber = rgb(0.85, 0.47, 0.02);
  const blue = rgb(0.11, 0.38, 0.87);

  const w = 595;
  const mx = 40;
  const contentW = w - mx * 2;
  let y = 802;

  let logoDrawn = false;
  if (logoBase64) {
    try {
      const base64Data = logoBase64.replace(/^data:image\/(png|jpe?g);base64,/, "");
      const imageBytes = Buffer.from(base64Data, "base64");
      let image;
      if (logoBase64.includes("image/png")) {
        image = await pdfDoc.embedPng(imageBytes);
      } else {
        image = await pdfDoc.embedJpg(imageBytes);
      }
      const maxW = 148;
      const maxH = 52;
      const scale = Math.min(maxW / image.width, maxH / image.height, 1);
      const drawW = image.width * scale;
      const drawH = image.height * scale;
      page.drawImage(image, { x: mx, y: y - drawH + 22, width: drawW, height: drawH });
      logoDrawn = true;
    } catch {
      logoDrawn = false;
    }
  }

  if (!logoDrawn) {
    page.drawText(studioName, { x: mx, y, font: helveticaBold, size: 18, color: black });
  }
  page.drawText(invoiceTitle, {
    x: w - mx - helveticaBold.widthOfTextAtSize(invoiceTitle, 22),
    y,
    font: helveticaBold,
    size: 22,
    color: black,
  });

  y -= 18;
  if (!logoDrawn) {
    page.drawText(t.studioManagement, { x: mx, y, font: helvetica, size: 9, color: gray });
  }
  const codeW = helvetica.widthOfTextAtSize(booking.booking_code, 10);
  page.drawText(booking.booking_code, {
    x: w - mx - codeW,
    y,
    font: helvetica,
    size: 10,
    color: gray,
  });

  y -= 14;
  const dateW = helvetica.widthOfTextAtSize(now, 9);
  page.drawText(now, { x: w - mx - dateW, y, font: helvetica, size: 9, color: gray });

  y -= 16;
  page.drawLine({ start: { x: mx, y }, end: { x: w - mx, y }, thickness: 1, color: lightGray });

  y -= 24;
  page.drawText(t.clientDetail, { x: mx, y, font: helveticaBold, size: 8, color: gray });
  y -= 18;
  page.drawText(booking.client_name, { x: mx, y, font: helveticaBold, size: 12, color: black });
  y -= 16;
  page.drawText(booking.client_whatsapp || "-", { x: mx, y, font: helvetica, size: 10, color: gray });

  y -= 30;
  const colX = [mx, mx + 200, mx + 320, w - mx];
  const headers = [t.service, t.schedule, t.status, t.total];
  page.drawRectangle({
    x: mx,
    y: y - 4,
    width: contentW,
    height: 28,
    color: rgb(0.976, 0.98, 0.984),
  });
  headers.forEach((header, index) => {
    const tx =
      index === 3
        ? colX[index] - helveticaBold.widthOfTextAtSize(header, 8)
        : colX[index] + 8;
    page.drawText(header, { x: tx, y: y + 6, font: helveticaBold, size: 8, color: gray });
  });

  y -= 6;
  page.drawLine({ start: { x: mx, y }, end: { x: w - mx, y }, thickness: 0.5, color: lightGray });

  y -= 20;
  page.drawText(serviceName, { x: colX[0] + 8, y, font: helvetica, size: 10, color: black });
  page.drawText(sessionDate, { x: colX[1] + 8, y, font: helvetica, size: 10, color: black });
  const statusColor =
    paymentStatus === t.paid ? green : paymentStatus === t.pendingVerification ? blue : amber;
  page.drawText(paymentStatus, {
    x: colX[2] + 8,
    y,
    font: helveticaBold,
    size: 10,
    color: statusColor,
  });
  const totalStr = formatCurrency(shownTotal);
  page.drawText(totalStr, {
    x: colX[3] - helvetica.widthOfTextAtSize(totalStr, 10),
    y,
    font: helvetica,
    size: 10,
    color: black,
  });

  y -= 14;
  page.drawLine({
    start: { x: mx, y },
    end: { x: w - mx, y },
    thickness: 0.5,
    color: rgb(0.95, 0.96, 0.96),
  });

  if (isFinalStage) {
    y -= 28;
    page.drawText(t.adjustments, { x: mx, y, font: helveticaBold, size: 10, color: black });
    y -= 14;

    if (adjustments.length === 0) {
      page.drawText("-", { x: mx, y, font: helvetica, size: 10, color: gray });
      y -= 8;
    } else {
      adjustments.forEach((item) => {
        const reason = item.reason || t.noReason;
        page.drawText(item.label, { x: mx, y, font: helveticaBold, size: 10, color: black });
        const amountText = formatCurrency(item.amount);
        page.drawText(amountText, {
          x: w - mx - helveticaBold.widthOfTextAtSize(amountText, 10),
          y,
          font: helveticaBold,
          size: 10,
          color: black,
        });
        y -= 14;
        page.drawText(reason, { x: mx + 8, y, font: helvetica, size: 9, color: gray });
        y -= 16;
      });
    }
  }

  y -= 18;
  const sumX = w - mx - 220;
  const sumValX = w - mx;

  page.drawText(t.subTotal, { x: sumX, y, font: helvetica, size: 10, color: black });
  const subTotalText = formatCurrency(booking.total_price);
  page.drawText(subTotalText, {
    x: sumValX - helvetica.widthOfTextAtSize(subTotalText, 10),
    y,
    font: helvetica,
    size: 10,
    color: black,
  });

  if (isFinalStage) {
    y -= 22;
    page.drawText(t.adjustmentTotal, { x: sumX, y, font: helvetica, size: 10, color: black });
    const adjText = formatCurrency(adjustmentsTotal);
    page.drawText(adjText, {
      x: sumValX - helvetica.widthOfTextAtSize(adjText, 10),
      y,
      font: helvetica,
      size: 10,
      color: black,
    });
  }

  y -= 22;
  page.drawText(t.dpPaid, { x: sumX, y, font: helvetica, size: 10, color: black });
  const dpText = `- ${formatCurrency(booking.dp_paid)}`;
  page.drawText(dpText, {
    x: sumValX - helvetica.widthOfTextAtSize(dpText, 10),
    y,
    font: helvetica,
    size: 10,
    color: black,
  });

  y -= 14;
  page.drawLine({ start: { x: sumX, y }, end: { x: sumValX, y }, thickness: 1.5, color: black });

  y -= 20;
  page.drawText(t.remainingPayment, { x: sumX, y, font: helveticaBold, size: 13, color: black });
  const remainingText = formatCurrency(remaining);
  page.drawText(remainingText, {
    x: sumValX - helveticaBold.widthOfTextAtSize(remainingText, 13),
    y,
    font: helveticaBold,
    size: 13,
    color: black,
  });

  y -= 60;
  page.drawLine({ start: { x: mx, y }, end: { x: w - mx, y }, thickness: 0.5, color: lightGray });
  y -= 16;
  const footerText = t.footerText;
  const footerWidth = helvetica.widthOfTextAtSize(footerText, 9);
  page.drawText(footerText, {
    x: (w - footerWidth) / 2,
    y,
    font: helvetica,
    size: 9,
    color: gray,
  });

  const pdfBytes = await pdfDoc.save();
  const filename = `${isFinalStage ? "Final-Invoice" : "Invoice"}-${booking.booking_code}.pdf`;

  return new NextResponse(Buffer.from(pdfBytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="${filename}"`,
    },
  });
}
