import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { formatSessionDate } from "@/utils/format-date";
import { resolveBookingCalendarSessions } from "@/lib/booking-calendar-sessions";
import { getInvoicePayloadCached } from "@/lib/public-invoice-data";
import {
  getFinalAdjustmentsTotal,
  getRemainingFinalPayment,
  getSettlementStatus,
  normalizeFinalAdjustments,
} from "@/lib/final-settlement";
import {
  normalizeLegacyServiceRecord,
  normalizeBookingServiceSelections,
} from "@/lib/booking-services";
import {
  getInitialBookingPriceBreakdown,
  resolveSpecialOfferSnapshotFromExtraFields,
} from "@/lib/booking-special-offer";
import { getTenantConfig } from "@/lib/tenant-config";
import { shouldHideTenantBranding } from "@/lib/tenant-branding";

export const dynamic = "force-dynamic";

const NO_STORE_HEADERS = {
  "Cache-Control": "no-store, no-cache, max-age=0, must-revalidate",
  Pragma: "no-cache",
  Expires: "0",
} as const;

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

function formatCurrency(n: number) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(n);
}

function wrapTextLines(
  text: string,
  font: PDFFont,
  size: number,
  maxWidth: number,
): string[] {
  if (!text.trim()) return [];

  const lines: string[] = [];
  const paragraphs = text.replace(/\r/g, "").split("\n");

  for (const paragraph of paragraphs) {
    if (!paragraph.trim()) {
      lines.push("");
      continue;
    }

    const words = paragraph.split(/\s+/).filter(Boolean);
    let currentLine = "";

    const pushLine = () => {
      if (currentLine) {
        lines.push(currentLine);
        currentLine = "";
      }
    };

    for (const word of words) {
      const candidate = currentLine ? `${currentLine} ${word}` : word;
      if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
        currentLine = candidate;
        continue;
      }

      if (currentLine) {
        pushLine();
      }

      if (font.widthOfTextAtSize(word, size) <= maxWidth) {
        currentLine = word;
        continue;
      }

      let chunk = "";
      for (const ch of word) {
        const nextChunk = `${chunk}${ch}`;
        if (font.widthOfTextAtSize(nextChunk, size) <= maxWidth) {
          chunk = nextChunk;
        } else {
          if (chunk) lines.push(chunk);
          chunk = ch;
        }
      }
      currentLine = chunk;
    }

    pushLine();
  }

  return lines;
}

const labels: Record<string, Record<string, string>> = {
  id: {
    clientDetail: "DETAIL KLIEN",
    service: "Layanan",
    schedule: "Jadwal",
    status: "Status",
    total: "Total",
    packageDescription: "Deskripsi Paket",
    reason: "Alasan",
    noDescription: "Tidak ada deskripsi paket.",
    subTotal: "Sub Total",
    dpPaid: "DP Dibayar",
    remainingPayment: "Sisa Pembayaran",
    paid: "Lunas",
    unpaid: "Belum Lunas",
    pendingVerification: "Menunggu Verifikasi",
    studioManagement: "Studio Management",
    footerText:
      "Terima kasih atas kepercayaan Anda. Invoice ini digenerate otomatis oleh Client Desk.",
    defaultServiceName: "Layanan",
    invoice: "INVOICE",
    finalInvoice: "INVOICE FINAL",
    adjustments: "Penyesuaian Akhir",
    adjustmentTotal: "Total Penyesuaian",
    noReason: "Tanpa catatan",
    initialBreakdown: "Rincian Harga Awal",
    initialPackage: "Paket Awal",
    initialAddon: "Add-on Awal",
    addOnSection: "Add On",
    accommodationFee: "Akomodasi",
    specialDiscount: "Diskon Khusus",
  },
  en: {
    clientDetail: "CLIENT DETAIL",
    service: "Service",
    schedule: "Schedule",
    status: "Status",
    total: "Total",
    packageDescription: "Package Description",
    reason: "Reason",
    noDescription: "No package description.",
    subTotal: "Sub Total",
    dpPaid: "DP Paid",
    remainingPayment: "Remaining Payment",
    paid: "Paid",
    unpaid: "Unpaid",
    pendingVerification: "Pending Verification",
    studioManagement: "Studio Management",
    footerText:
      "Thank you for your trust. This invoice was auto-generated by Client Desk.",
    defaultServiceName: "Service",
    invoice: "INVOICE",
    finalInvoice: "FINAL INVOICE",
    adjustments: "Final Adjustments",
    adjustmentTotal: "Adjustment Total",
    noReason: "No note",
    initialBreakdown: "Initial Price Breakdown",
    initialPackage: "Initial Package",
    initialAddon: "Initial Add-on",
    addOnSection: "Add On",
    accommodationFee: "Accommodation",
    specialDiscount: "Special Discount",
  },
};

const UNBRANDED_FOOTER_TEXT_BY_LANG: Record<string, string> = {
  id: "Terima kasih atas kepercayaan Anda. Invoice ini digenerate otomatis.",
  en: "Thank you for your trust. This invoice was auto-generated.",
};

async function resolveInvoiceLogoBytes(source: string) {
  const trimmed = source.trim();
  if (!trimmed) return null;

  const dataUriMatch = trimmed.match(/^data:image\/(png|jpe?g|webp);base64,(.+)$/i);
  if (dataUriMatch) {
    const mime = dataUriMatch[1].toLowerCase();
    const base64Payload = dataUriMatch[2];
    if (mime === "webp") {
      return null;
    }
    return {
      bytes: Buffer.from(base64Payload, "base64"),
      format: mime === "png" ? "png" : "jpg",
    } as const;
  }

  try {
    const response = await fetch(trimmed, { cache: "no-store" });
    if (!response.ok) return null;
    const contentType = (response.headers.get("content-type") || "").toLowerCase();
    if (!contentType.startsWith("image/")) return null;
    if (
      !contentType.includes("png") &&
      !contentType.includes("jpeg") &&
      !contentType.includes("jpg")
    ) {
      return null;
    }
    const bytes = Buffer.from(await response.arrayBuffer());
    return {
      bytes,
      format: contentType.includes("png") ? "png" : "jpg",
    } as const;
  } catch {
    return null;
  }
}

export async function GET(request: NextRequest) {
  const code = request.nextUrl.searchParams.get("code");
  const lang = request.nextUrl.searchParams.get("lang") || "id";
  const stage = request.nextUrl.searchParams.get("stage") || "initial";
  const t = labels[lang] || labels.id;
  const tenant = await getTenantConfig();
  const hideTenantBranding = shouldHideTenantBranding({
    id: tenant.id,
    domain: tenant.domain,
  });

  if (!code) {
    return NextResponse.json(
      { error: "Booking code required" },
      { status: 400, headers: NO_STORE_HEADERS },
    );
  }

  const cachedPayload = await getInvoicePayloadCached(code, stage, lang);
  if (!cachedPayload) {
    return NextResponse.json(
      { error: "Booking not found" },
      { status: 404, headers: NO_STORE_HEADERS },
    );
  }
  const { booking, profile } = cachedPayload;

  const studioName = profile?.studio_name || "Studio";
  const studioAddress = profile?.studio_address?.trim() || "";
  const logoSource = profile?.invoice_logo_url || null;
  const specialOffer = resolveSpecialOfferSnapshotFromExtraFields(booking.extra_fields);
  const adjustments = normalizeFinalAdjustments(booking.final_adjustments);
  const adjustmentsTotal = getFinalAdjustmentsTotal(adjustments);
  const isFinalStage = stage === "final";
  const invoiceTitle = isFinalStage ? t.finalInvoice : t.invoice;
  const remaining = isFinalStage
    ? getRemainingFinalPayment({
        total_price: booking.total_price,
        dp_paid: booking.dp_paid,
        final_adjustments: adjustments,
        final_payment_amount: booking.final_payment_amount,
        final_paid_at: booking.final_paid_at,
        settlement_status: booking.settlement_status,
        is_fully_paid: booking.is_fully_paid,
      })
    : Math.max(booking.total_price - booking.dp_paid, 0);
  const dateLocale = lang === "en" ? "en-US" : "id-ID";
  const sessionDate = booking.session_date
    ? formatSessionDate(booking.session_date, {
        locale: lang === "en" ? "en" : "id",
        dateOnly: true,
      })
    : "-";
  const sessionRows = resolveBookingCalendarSessions({
    eventType: booking.event_type,
    sessionDate: booking.session_date,
    extraFields: booking.extra_fields,
  });
  const scheduleEntries = (
    sessionRows.length > 0
      ? sessionRows.map((session) => {
          const formattedDate = formatSessionDate(session.sessionDate, {
            locale: lang === "en" ? "en" : "id",
            dateOnly: true,
          });
          if (session.label) {
            return `${session.label}: ${formattedDate}`;
          }
          return formattedDate;
        })
      : [sessionDate]
  ).filter((value) => value && value.trim().length > 0);
  const fallbackDateLabel = new Date().toLocaleDateString(dateLocale, {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const bookingDateLabel =
    typeof booking.booking_date === "string" && booking.booking_date.trim()
      ? formatSessionDate(booking.booking_date, {
          locale: lang === "en" ? "en" : "id",
          dateOnly: true,
        })
      : "-";
  const invoiceHeaderDate =
    bookingDateLabel && bookingDateLabel !== "-" ? bookingDateLabel : fallbackDateLabel;
  const legacyService = normalizeLegacyServiceRecord(booking.services);
  const serviceSelections = normalizeBookingServiceSelections(
    (booking as { booking_services?: unknown[] }).booking_services,
    booking.services,
  );
  const initialBreakdown = getInitialBookingPriceBreakdown({
    totalPrice: booking.total_price,
    serviceSelections,
    legacyServicePrice: legacyService?.price ?? booking.total_price,
    extraFields: booking.extra_fields,
  });
  const mainServiceSelections = serviceSelections.filter(
    (selection) => selection.kind === "main",
  );
  const addonServiceSelections = serviceSelections.filter(
    (selection) => selection.kind === "addon",
  );
  type InvoiceServiceRow = {
    id: string;
    name: string;
    description: string;
    price: number;
    group: "main" | "addon";
  };
  const mappedServiceRows: InvoiceServiceRow[] = [
    ...mainServiceSelections.map((selection) => ({
      id: selection.id,
      name: selection.service.name || t.defaultServiceName,
      description: selection.service.description?.trim() || "",
      price:
        typeof selection.service.price === "number"
          ? Math.max(selection.service.price, 0)
          : 0,
      group: "main" as const,
    })),
    ...addonServiceSelections.map((selection) => ({
      id: selection.id,
      name: selection.service.name || t.defaultServiceName,
      description: selection.service.description?.trim() || "",
      price:
        typeof selection.service.price === "number"
          ? Math.max(selection.service.price, 0)
          : 0,
      group: "addon" as const,
    })),
  ];
  let serviceRows =
    mappedServiceRows.length > 0
      ? mappedServiceRows
      : [
          {
            id: legacyService?.id || "",
            name: legacyService?.name || t.defaultServiceName,
            description: legacyService?.description?.trim() || "",
            price:
              typeof legacyService?.price === "number"
                ? Math.max(legacyService.price, 0)
                : 0,
            group: "main" as const,
          },
        ];
  const currentServiceRowsTotal = serviceRows.reduce(
    (sum, row) => sum + row.price,
    0,
  );
  const missingAddonTotal = Math.max(
    Math.min(
      initialBreakdown.addonTotal,
      Math.max(booking.total_price - currentServiceRowsTotal, 0),
    ),
    0,
  );
  if (addonServiceSelections.length === 0 && missingAddonTotal > 0) {
    serviceRows = [
      ...serviceRows,
      {
        id: "initial-addon-fallback",
        name: t.initialAddon,
        description:
          specialOffer?.link_name?.trim() && specialOffer.link_name.trim().length > 0
            ? specialOffer.link_name.trim()
            : "",
        price: missingAddonTotal,
        group: "addon" as const,
      },
    ];
  }
  const serviceDescriptionById: Record<string, string> = {};
  serviceSelections.forEach((selection) => {
    const serviceId = selection.service.id;
    if (!serviceId) return;
    const description = selection.service.description?.trim();
    if (description) {
      serviceDescriptionById[serviceId] = description;
    }
  });
  if (legacyService?.id && legacyService.description?.trim()) {
    serviceDescriptionById[legacyService.id] = legacyService.description.trim();
  }

  const unresolvedAdjustmentServiceIds = Array.from(
    new Set(
      adjustments
        .map((item) => item.service_id || "")
        .filter((serviceId) => serviceId && !serviceDescriptionById[serviceId]),
    ),
  );
  if (unresolvedAdjustmentServiceIds.length > 0) {
    const { data: adjustmentServices } = await supabaseAdmin
      .from("services")
      .select("id, description")
      .eq("user_id", booking.user_id)
      .in("id", unresolvedAdjustmentServiceIds);

    (adjustmentServices || []).forEach((service) => {
      if (!service.id) return;
      const description =
        typeof service.description === "string"
          ? service.description.trim()
          : "";
      if (description) {
        serviceDescriptionById[service.id] = description;
      }
    });
  }

  const settlementStatus = getSettlementStatus(booking.settlement_status);
  const paymentStatus =
    isFinalStage && settlementStatus === "submitted"
      ? t.pendingVerification
      : booking.is_fully_paid
        ? t.paid
        : t.unpaid;

  const pdfDoc = await PDFDocument.create();
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const black = rgb(0.1, 0.1, 0.1);
  const gray = rgb(0.42, 0.44, 0.47);
  const lightGray = rgb(0.9, 0.91, 0.92);
  const green = rgb(0.086, 0.64, 0.26);
  const amber = rgb(0.85, 0.47, 0.02);
  const blue = rgb(0.11, 0.38, 0.87);

  const PAGE_WIDTH = 595;
  const PAGE_HEIGHT = 842;
  const MARGIN_X = 40;
  const TOP_Y = 802;
  const BOTTOM_Y = 50;
  const contentW = PAGE_WIDTH - MARGIN_X * 2;

  let page: PDFPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = TOP_Y;

  const addPage = () => {
    page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = TOP_Y;
  };

  const ensureSpace = (requiredHeight: number) => {
    if (y - requiredHeight < BOTTOM_Y) {
      addPage();
    }
  };

  const drawHorizontalLine = (
    startX: number,
    endX: number,
    thickness: number,
    color = lightGray,
  ) => {
    page.drawLine({
      start: { x: startX, y },
      end: { x: endX, y },
      thickness,
      color,
    });
  };

  const drawWrappedText = (params: {
    text: string;
    x: number;
    maxWidth: number;
    font: PDFFont;
    size: number;
    color: ReturnType<typeof rgb>;
    lineHeight: number;
  }) => {
    const lines = wrapTextLines(
      params.text,
      params.font,
      params.size,
      params.maxWidth,
    );

    if (lines.length === 0) {
      ensureSpace(params.lineHeight);
      page.drawText(t.noDescription, {
        x: params.x,
        y,
        font: params.font,
        size: params.size,
        color: params.color,
      });
      y -= params.lineHeight;
      return;
    }

    lines.forEach((line) => {
      ensureSpace(params.lineHeight);
      if (line) {
        page.drawText(line, {
          x: params.x,
          y,
          font: params.font,
          size: params.size,
          color: params.color,
        });
      }
      y -= params.lineHeight;
    });
  };

  let logoDrawn = false;
  let logoBottomY = y;
  if (logoSource) {
    try {
      const logoBytes = await resolveInvoiceLogoBytes(logoSource);
      if (logoBytes) {
        const image =
          logoBytes.format === "png"
            ? await pdfDoc.embedPng(logoBytes.bytes)
            : await pdfDoc.embedJpg(logoBytes.bytes);
        const maxW = 148;
        const maxH = 52;
        const scale = Math.min(maxW / image.width, maxH / image.height, 1);
        const drawW = image.width * scale;
        const drawH = image.height * scale;
        const logoY = y - drawH + 22;
        page.drawImage(image, {
          x: MARGIN_X,
          y: logoY,
          width: drawW,
          height: drawH,
        });
        logoBottomY = logoY;
        logoDrawn = true;
      }
    } catch {
      logoDrawn = false;
    }
  }

  let leftBlockBottomY = logoDrawn ? logoBottomY : y;
  if (!logoDrawn) {
    page.drawText(studioName, {
      x: MARGIN_X,
      y,
      font: helveticaBold,
      size: 18,
      color: black,
    });
    leftBlockBottomY = y - 18;
  }

  page.drawText(invoiceTitle, {
    x: PAGE_WIDTH - MARGIN_X - helveticaBold.widthOfTextAtSize(invoiceTitle, 22),
    y,
    font: helveticaBold,
    size: 22,
    color: black,
  });

  const codeY = y - 18;
  if (!logoDrawn) {
    page.drawText(t.studioManagement, {
      x: MARGIN_X,
      y: codeY,
      font: helvetica,
      size: 9,
      color: gray,
    });
    leftBlockBottomY = Math.min(leftBlockBottomY, codeY - 9);
  }

  const codeW = helvetica.widthOfTextAtSize(booking.booking_code, 10);
  page.drawText(booking.booking_code, {
    x: PAGE_WIDTH - MARGIN_X - codeW,
    y: codeY,
    font: helvetica,
    size: 10,
    color: gray,
  });

  const dateY = codeY - 14;
  const dateW = helvetica.widthOfTextAtSize(invoiceHeaderDate, 9);
  page.drawText(invoiceHeaderDate, {
    x: PAGE_WIDTH - MARGIN_X - dateW,
    y: dateY,
    font: helvetica,
    size: 9,
    color: gray,
  });
  const rightBlockBottomY = dateY - 9;

  if (studioAddress) {
    const addressLines = wrapTextLines(studioAddress, helvetica, 8.5, 250);
    if (addressLines.length > 0) {
      const addressLineHeight = 10;
      const addressStartY = (logoDrawn ? logoBottomY : leftBlockBottomY) - 12;
      addressLines.forEach((line, index) => {
        page.drawText(line, {
          x: MARGIN_X,
          y: addressStartY - index * addressLineHeight,
          font: helvetica,
          size: 8.5,
          color: gray,
        });
      });
      const addressBottomY =
        addressStartY - (addressLines.length - 1) * addressLineHeight - 8.5;
      leftBlockBottomY = Math.min(leftBlockBottomY, addressBottomY);
    }
  }

  const headerBottomY = Math.min(leftBlockBottomY, rightBlockBottomY);
  y = headerBottomY - 8;
  drawHorizontalLine(MARGIN_X, PAGE_WIDTH - MARGIN_X, 1);

  y -= 24;
  page.drawText(t.clientDetail, {
    x: MARGIN_X,
    y,
    font: helveticaBold,
    size: 8,
    color: gray,
  });

  y -= 18;
  page.drawText(booking.client_name, {
    x: MARGIN_X,
    y,
    font: helveticaBold,
    size: 12,
    color: black,
  });

  y -= 16;
  page.drawText(booking.client_whatsapp || "-", {
    x: MARGIN_X,
    y,
    font: helvetica,
    size: 10,
    color: gray,
  });

  y -= 30;
  const colX = [MARGIN_X, MARGIN_X + 200, MARGIN_X + 320, PAGE_WIDTH - MARGIN_X];
  const headers = [t.service, t.schedule, t.status, t.total];
  page.drawRectangle({
    x: MARGIN_X,
    y: y - 4,
    width: contentW,
    height: 28,
    color: rgb(0.976, 0.98, 0.984),
  });

  headers.forEach((header, index) => {
    const tx =
      index === 3
        ? colX[index] - helveticaBold.widthOfTextAtSize(header, 8)
        : colX[index] + 8;
    page.drawText(header, {
      x: tx,
      y: y + 6,
      font: helveticaBold,
      size: 8,
      color: gray,
    });
  });

  y -= 6;
  drawHorizontalLine(MARGIN_X, PAGE_WIDTH - MARGIN_X, 0.5);

  const statusColor =
    paymentStatus === t.paid
      ? green
      : paymentStatus === t.pendingVerification
        ? blue
        : amber;

  let addonSectionDrawn = false;
  serviceRows.forEach((serviceRow) => {
    if (serviceRow.group === "addon" && !addonSectionDrawn) {
      ensureSpace(34);
      y -= 14;
      page.drawRectangle({
        x: MARGIN_X,
        y: y - 4,
        width: contentW,
        height: 22,
        color: rgb(0.98, 0.986, 0.992),
      });
      page.drawText(t.addOnSection, {
        x: MARGIN_X + 8,
        y: y + 4,
        font: helveticaBold,
        size: 8,
        color: gray,
      });
      y -= 8;
      drawHorizontalLine(MARGIN_X, PAGE_WIDTH - MARGIN_X, 0.5);
      addonSectionDrawn = true;
    }

    const normalizedDescription = serviceRow.description || t.noDescription;
    const descriptionLines = wrapTextLines(
      normalizedDescription,
      helvetica,
      9,
      colX[1] - colX[0] - 16,
    );
    const scheduleText =
      serviceRow.group === "addon"
        ? "-"
        : scheduleEntries.length > 0
          ? scheduleEntries.join("\n")
          : "-";
    const scheduleLines = wrapTextLines(
      scheduleText,
      helvetica,
      9,
      colX[2] - colX[1] - 16,
    );
    const detailLines = Math.max(descriptionLines.length, 1);
    const scheduleLineCount = Math.max(scheduleLines.length, 1);
    const contentLines = Math.max(detailLines, scheduleLineCount);
    const rowHeight = 14 + contentLines * 12 + 8;

    ensureSpace(rowHeight + 4);
    y -= 20;

    page.drawText(serviceRow.name, {
      x: colX[0] + 8,
      y,
      font: helvetica,
      size: 10,
      color: black,
    });
    scheduleLines.forEach((line, index) => {
      const textLine = line || (index === 0 ? "-" : "");
      if (!textLine) return;
      page.drawText(textLine, {
        x: colX[1] + 8,
        y: y - index * 12,
        font: helvetica,
        size: 9,
        color: black,
      });
    });
    page.drawText(paymentStatus, {
      x: colX[2] + 8,
      y,
      font: helveticaBold,
      size: 10,
      color: statusColor,
    });

    const totalStr = formatCurrency(serviceRow.price);
    page.drawText(totalStr, {
      x: colX[3] - helvetica.widthOfTextAtSize(totalStr, 10),
      y,
      font: helvetica,
      size: 10,
      color: black,
    });

    y -= 14;
    descriptionLines.forEach((line, index) => {
      const textLine = line || (index === 0 ? t.noDescription : "");
      if (!textLine) return;
      page.drawText(textLine, {
        x: colX[0] + 8,
        y,
        font: helvetica,
        size: 9,
        color: gray,
      });
      y -= 12;
    });

    if (contentLines > detailLines) {
      y -= (contentLines - detailLines) * 12;
    }

    y -= 8;
    drawHorizontalLine(
      MARGIN_X,
      PAGE_WIDTH - MARGIN_X,
      0.5,
      rgb(0.95, 0.96, 0.96),
    );
  });

  if (specialOffer) {
    y -= 20;
    ensureSpace(92);
    page.drawText(t.initialBreakdown, {
      x: MARGIN_X,
      y,
      font: helveticaBold,
      size: 10,
      color: black,
    });

    const breakdownRows: Array<{ label: string; value: string }> = [
      { label: t.initialPackage, value: formatCurrency(specialOffer.package_total) },
      { label: t.initialAddon, value: formatCurrency(specialOffer.addon_total) },
    ];

    if (specialOffer.accommodation_fee > 0) {
      breakdownRows.push({
        label: t.accommodationFee,
        value: formatCurrency(specialOffer.accommodation_fee),
      });
    }

    if (specialOffer.discount_amount > 0) {
      breakdownRows.push({
        label: t.specialDiscount,
        value: `- ${formatCurrency(specialOffer.discount_amount)}`,
      });
    }

    y -= 16;
    breakdownRows.forEach((row) => {
      ensureSpace(14);
      page.drawText(row.label, {
        x: MARGIN_X + 8,
        y,
        font: helvetica,
        size: 9,
        color: gray,
      });
      page.drawText(row.value, {
        x: PAGE_WIDTH - MARGIN_X - helvetica.widthOfTextAtSize(row.value, 9),
        y,
        font: helvetica,
        size: 9,
        color: black,
      });
      y -= 14;
    });
    y -= 4;
    drawHorizontalLine(MARGIN_X, PAGE_WIDTH - MARGIN_X, 0.5, rgb(0.95, 0.96, 0.96));
  }

  if (isFinalStage) {
    y -= 22;
    ensureSpace(28);
    page.drawText(t.adjustments, {
      x: MARGIN_X,
      y,
      font: helveticaBold,
      size: 10,
      color: black,
    });
    y -= 14;

    if (adjustments.length === 0) {
      ensureSpace(12);
      page.drawText("-", {
        x: MARGIN_X,
        y,
        font: helvetica,
        size: 10,
        color: gray,
      });
      y -= 12;
    } else {
      adjustments.forEach((item) => {
        ensureSpace(24);
        page.drawText(item.label, {
          x: MARGIN_X,
          y,
          font: helveticaBold,
          size: 10,
          color: black,
        });

        const amountText = formatCurrency(item.amount);
        page.drawText(amountText, {
          x: PAGE_WIDTH - MARGIN_X - helveticaBold.widthOfTextAtSize(amountText, 10),
          y,
          font: helveticaBold,
          size: 10,
          color: black,
        });

        y -= 14;
        const serviceDescription =
          (item.service_id && serviceDescriptionById[item.service_id]) || "-";
        const reason = item.reason || t.noReason;
        drawWrappedText({
          text:
            `${t.packageDescription}: ${serviceDescription}\n` +
            `${t.reason}: ${reason}`,
          x: MARGIN_X + 8,
          maxWidth: contentW - 16,
          font: helvetica,
          size: 9,
          color: gray,
          lineHeight: 12,
        });
        y -= 4;
      });
    }
  }

  y -= 14;
  ensureSpace(isFinalStage ? 120 : 96);

  const sumX = PAGE_WIDTH - MARGIN_X - 220;
  const sumValX = PAGE_WIDTH - MARGIN_X;

  page.drawText(t.subTotal, {
    x: sumX,
    y,
    font: helvetica,
    size: 10,
    color: black,
  });
  const subTotalText = formatCurrency(booking.total_price);
  page.drawText(subTotalText, {
    x: sumValX - helvetica.widthOfTextAtSize(subTotalText, 10),
    y,
    font: helvetica,
    size: 10,
    color: black,
  });

  if (isFinalStage) {
    y -= 22;
    page.drawText(t.adjustmentTotal, {
      x: sumX,
      y,
      font: helvetica,
      size: 10,
      color: black,
    });
    const adjText = formatCurrency(adjustmentsTotal);
    page.drawText(adjText, {
      x: sumValX - helvetica.widthOfTextAtSize(adjText, 10),
      y,
      font: helvetica,
      size: 10,
      color: black,
    });
  }

  y -= 22;
  page.drawText(t.dpPaid, {
    x: sumX,
    y,
    font: helvetica,
    size: 10,
    color: black,
  });
  const dpText = `- ${formatCurrency(booking.dp_paid)}`;
  page.drawText(dpText, {
    x: sumValX - helvetica.widthOfTextAtSize(dpText, 10),
    y,
    font: helvetica,
    size: 10,
    color: black,
  });

  y -= 14;
  drawHorizontalLine(sumX, sumValX, 1.5, black);

  y -= 20;
  page.drawText(t.remainingPayment, {
    x: sumX,
    y,
    font: helveticaBold,
    size: 13,
    color: black,
  });
  const remainingText = formatCurrency(remaining);
  page.drawText(remainingText, {
    x: sumValX - helveticaBold.widthOfTextAtSize(remainingText, 13),
    y,
    font: helveticaBold,
    size: 13,
    color: black,
  });

  y -= 50;
  ensureSpace(30);
  drawHorizontalLine(MARGIN_X, PAGE_WIDTH - MARGIN_X, 0.5);

  y -= 16;
  const footerText = hideTenantBranding
    ? UNBRANDED_FOOTER_TEXT_BY_LANG[lang] || UNBRANDED_FOOTER_TEXT_BY_LANG.id
    : t.footerText;
  const footerWidth = helvetica.widthOfTextAtSize(footerText, 9);
  page.drawText(footerText, {
    x: (PAGE_WIDTH - footerWidth) / 2,
    y,
    font: helvetica,
    size: 9,
    color: gray,
  });

  const pdfBytes = await pdfDoc.save();
  const filename = `${isFinalStage ? "Final-Invoice" : "Invoice"}-${booking.booking_code}.pdf`;

  return new NextResponse(Buffer.from(pdfBytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="${filename}"`,
      ...NO_STORE_HEADERS,
    },
  });
}
